FROM node AS lucifer  

# Create app directory
WORKDIR /app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package.json ./

RUN npm install
# If you are building your code for production
# RUN npm ci --only=production

# Bundle app source
COPY . .

#we can add a multi-stage scenario here

FROM alpine:3.14
WORKDIR /app1

COPY --from=lucifer /app .

#we added a new light image



EXPOSE 7777
ENTRYPOINT ["server.js"]

